# Site settings
title: Matthew Sessions
subtitle: All things I work on
email: shichongrui@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matthewsessions.com" # the base hostname & protocol for your site
author: Matthew Sessions

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/shichongrui
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/matthew-sessions-9ba85167/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/shichongrui

# Build settings
markdown: kramdown

force_polling: true

sass:
  style: compressed
  sass_dir: _sass
